#!/usr/bin/expect -f
set timeout 30
exp_internal 1
spawn ssh -o PubkeyAuthentication=no root@200.97.163.236
expect {
  -re "(?i)password:" {
    sleep 0.5
    send "Photoshop09@\r"
    exp_continue
  }
  -re "(?i)permission denied" {
    puts "FAILED: Permission denied"
    exit 1
  }
  "# " {
    send "echo 'SUCCESSFUL_LOGIN'\r"
    expect "# "
    send "whoami && pm2 status\r"
    expect "# "
    send "exit\r"
  }
}
expect eof
